# -*- coding: utf-8 -*-
"""Masterclass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ybtflds0ewZm905s0Pi7kiAJIIQCgw-
"""

pip install pandas

pip install requests

import requests

response = requests.get('https://zucwflxqsxrsmwseehqvjmnx2u0cdigp.lambda-url.ap-south-1.on.aws/mentorskool/v1/sales',headers= {"access_token":"fe66583bfe5185048c66571293e0d358"})

response

print("Content:",response.text)



print("Status code:",response.status_code)
print(response.raise_for_status())